# Project information
site_name: Health Data Science Sandbox
site_url: https://conor-ohare.github.io/amazing/
site_description: 'Supporting training and research in health data science'
docs_dir: develop
site_dir: site

# Repository
repo_name: hds-sandbox
repo_url: https://github.com/hds-sandbox

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  palette: 
    # Palette toggle for light mode
    - scheme: brightness
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    logo: logo2

extra_css:
  - stylesheets/extra.css

# Plugins

plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hds-sandbox
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ucph_heads


# Extensions

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

# Page tree
nav:
  - Home: index.md
  - About: about/about.md
  - News: news/news.md
  - Access: 
      - 'Computerome': access/Computerome.md
      - 'UCloud': access/UCloud.md
  - Datasets: datasets/datapolicy.md
  - Modules:
      - modules/index.md
      - 'Genomics':
        - 'Introduction to Next Generation Sequencing Data': https://hds-sandbox.github.io/NGS_summer_course_Aarhus/
      - 'Transcriptomics': # modules/transcriptomics.md
        - 'Bulk RNAseq': https://hds-sandbox.github.io/bulk_RNAseq_course/
        - 'Single-Cell RNAseq': https://hds-sandbox.github.io/scRNASeq_course/
  - Contact: contact/contact.md
   
